In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('clean_netflix.csv')

In [3]:
df.head(2)

,show_id,type,title,director,cast,country,release_year,rating,listed_in,description,added_year,added_month,added_day,duration_minutes
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,David Attenborough,United States,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0,25.0,90.000000
1,2,TV Show,Blood & Water,Rajiv Chilaka,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0,24.0,99.577187

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   show_id           8807 non-null   int64
 1   type              8807 non-null   object
 2   title             8807 non-null   object
 3   director          8807 non-null   object
 4   cast              8807 non-null   object
 5   country           8807 non-null   object
 6   release_year      8807 non-null   int64
 7   rating            8807 non-null   object
 8   listed_in         8807 non-null   object
 9   description       8807 non-null   object
 10  added_year        8807 non-null   float64
 11  added_month       8807 non-null   float64
 12  added_day         8807 non-null   float64
 13  duration_minutes  8807 non-null   float64
dtypes: float64(4), int64(2), object(8)
memory usage: 963.4+ KB

In [5]:
### check the null values 

df.isnull().sum()

show_id             0
type                0
title               0
director            0
cast                0
country             0
release_year        0
rating              0
listed_in           0
description         0
added_year          0
added_month         0
added_day           0
duration_minutes    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
### fill the null values with the fill na

df['director']=df['director'].fillna(df['director'].mode()[0]) ## mode is only the object

In [8]:
df['cast']=df['cast'].fillna(df['cast'].mode()[0])

In [9]:
df['country']=df['country'].fillna(df['country'].mode()[0])

In [10]:
df['rating']=df['rating'].fillna(df['rating'].mode()[0])

In [11]:
df['duration']=df['duration'].fillna(df['duration'].mode()[0])

KeyError: 'duration'

In [12]:
#### firtsly convert the date in seperated from

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df.head(3)

KeyError: 'date_added'

In [13]:
df['year']=df['date_added'].dt.year

KeyError: 'date_added'

In [14]:
df['month']=df['date_added'].dt.month

KeyError: 'date_added'

In [15]:
df['day']=df['date_added'].dt.day

KeyError: 'date_added'

In [16]:
# filll the fulll value of year,month,daay
df['year']=df['year'].fillna(df['year'].mean())
df['month']=df['month'].fillna(df['month'].mean())
df['day']=df['day'].fillna(df['day'].mean())

KeyError: 'year'

In [17]:
df.head(4)

,show_id,type,title,director,cast,country,release_year,rating,listed_in,description,added_year,added_month,added_day,duration_minutes
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,David Attenborough,United States,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0,25.0,90.000000
1,2,TV Show,Blood & Water,Rajiv Chilaka,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0,24.0,99.577187
2,3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0,24.0,99.577187
3,4,TV Show,Jailbirds New Orleans,Rajiv Chilaka,David Attenborough,United States,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0,24.0,99.577187

In [18]:
### convert the data type of the year, month,day

df['year']=df['date_added'].astype(int)
df['month']=df['date_added'].astype(int)
df['day']=df['date_added'].astype(int)

KeyError: 'date_added'

In [19]:
df.isnull().sum()

show_id             0
type                0
title               0
director            0
cast                0
country             0
release_year        0
rating              0
listed_in           0
description         0
added_year          0
added_month         0
added_day           0
duration_minutes    0
dtype: int64

In [20]:
### date_added column is delete from the dataset after all process over it.
df.drop('date_added',axis=1,inplace=True)

KeyError: "['date_added'] not found in axis"

In [ ]:
## replace the value of s with whitespace

df['show_id']=df['show_id'].str.replace('s','')

In [21]:
df.head(2)

,show_id,type,title,director,cast,country,release_year,rating,listed_in,description,added_year,added_month,added_day,duration_minutes
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,David Attenborough,United States,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0,25.0,90.000000
1,2,TV Show,Blood & Water,Rajiv Chilaka,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0,24.0,99.577187

In [22]:
### convert the data type of show_id
df['show_id']=df['show_id'].astype(int)

In [23]:
## convert the data type of release_year
df['release_year']=df['release_year'].astype(int)

In [24]:
def convert_to_minutes(x):
    if pd.isna(x):
        return np.nan

    x = x.lower().strip()

    if 'min' in x:
        return int(x.replace('min', '').strip())

    if 'season' in x:          # case-insensitive, catches both 'season' and 'seasons'
        seasons = int(x.split()[0])
        return seasons * 450   # 450 min per season (≈ 7.5 h)

    return np.nan

df['duration_minutes']=df['duration'].apply(convert_to_minutes)

KeyError: 'duration'

In [25]:
df['duration_minutes']=df['duration_minutes'].fillna(df['duration'].mode()[0])

KeyError: 'duration'

In [26]:
df.drop('year',axis=1,inplace=True)
df.drop('month',axis=1,inplace=True)
df.drop('day',axis=1,inplace=True)

KeyError: "['year'] not found in axis"

In [27]:
df.drop('duration',axis=1,inplace=True)

KeyError: "['duration'] not found in axis"

In [28]:
## 
df.isnull().sum()

show_id             0
type                0
title               0
director            0
cast                0
country             0
release_year        0
rating              0
listed_in           0
description         0
added_year          0
added_month         0
added_day           0
duration_minutes    0
dtype: int64

In [29]:
df.head(10)

,show_id,type,title,director,cast,country,release_year,rating,listed_in,description,added_year,added_month,added_day,duration_minutes
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,David Attenborough,United States,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0,25.0,90.000000
1,2,TV Show,Blood & Water,Rajiv Chilaka,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0,24.0,99.577187
2,3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0,24.0,99.577187
3,4,TV Show,Jailbirds New Orleans,Rajiv Chilaka,David Attenborough,United States,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0,24.0,99.577187
4,5,TV Show,Kota Factory,Rajiv Chilaka,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0,24.0,99.577187
5,6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",United States,2021,TV-MA,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...,2021.0,9.0,24.0,99.577187
6,7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",United States,2021,PG,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,2021.0,9.0,24.0,91.000000
7,8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021.0,9.0,24.0,125.000000
8,9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021,TV-14,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021.0,9.0,24.0,99.577187
9,10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021,PG-13,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2021.0,9.0,24.0,104.000000

In [30]:
#####feature engneering
features=["type","director","cast","country","listed_in","description","release_year","duration_minutes"]
df_enc=df[features].fillna("")

###convert the text to numerical vector

In [31]:

from sklearn.feature_extraction.text import TfidfVectorizer
text_features=(
    df_enc['director']+''+
    df_enc['cast']+''+
    df_enc['country']+''+
    df_enc['listed_in']+''+
    df_enc['description']
)

tfidf=TfidfVectorizer(stop_words="english",max_features=5000)
text_encoded=tfidf.fit_transform(text_features)

In [32]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
type_encoded=encoder.fit_transform(df_enc[['type']])

In [33]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

numeric_encoded=scaler.fit_transform(df_enc[['release_year','duration_minutes']])

In [34]:
from scipy.sparse import hstack
final_features=hstack([text_encoded,type_encoded,numeric_encoded])

In [35]:
final_features

<COOrdinate sparse matrix of dtype 'float64'
	with 209670 stored elements and shape (8807, 5004)>

In [36]:
final_features=final_features.tocsr()

In [42]:
pickle.dump(final_features,open('final_features.pkl','wb'))

In [37]:
from sklearn.neighbors import NearestNeighbors
knn_model=NearestNeighbors(
    n_neighbors=6,
    metric='cosine',
    algorithm='brute'
    )
knn_model.fit(final_features)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=6)

 a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

###create a recommendation function

In [38]:
import pickle

In [40]:
with open('knn_model.pkl','wb') as f:
    pickle.dump(knn_model,f)